### ISSUE TITLE
Comparison to alternatives

### ISSUE THREAD

**Issue by tadejstanic** [gql-dal/greldal#36]
In the docs I've read this:

'GRelDAL currently isn't the ideal solution when the data set you are exposing through the API is too large to fit into memory.'

Could you explain a little bit more, why do you think this would be an issue?

**Comment by lorefnon** [comment]
GRelDAL transforms the data obtained from the database into the shape the graphql request expects. This transformation logic currently assumes that the entire response is in memory. 

So even if the underlying database connector and the query builder supports a streaming API we currently don't take advantage of it.

This does not impact my current use cases and I assume most of the common use cases, so I haven't spent any effort in this direction.

**Comment by tadejstanic** [comment]
Thx for the explanation. But isn't the problem with a large data set common to all graphql server implementations? I assume Hasura or join-monster, two solutions which produce optimized SQL queries, also have this problem. And even with a dataloader approcah, you can end up with the same problem. Please correct me if I'm wrong.

**Comment by lorefnon** [comment]
Yes, it is likely that most of the current implementations suffer from similar problems. 

But I can imagine that an advanced query planner deeply integrated with the database (or an inbuilt part of the database) could solve this by distributing the processing over a cluster and streaming the results to client. 

I just wanted to be clear to potential users that this is something we don't do.
